apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    opensearch.io: index:orderr
    opensearch.io: tenant:amdin_tenant
  name: playback-order
  description: Playback Order
  tags:
    - java
    - playback
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: audio-playback
